In [35]:
from platform import architecture
!pip install pandas
!pip install matplotlib
!pip install seaborn

Requirement already satisfied: pandas in ./venv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in ./venv/lib/python3.14/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: matplotlib in ./venv/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.14/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./venv/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in ./venv/lib/python3.14/site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.14/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in ./venv/lib/python3.14/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in ./venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: seaborn in ./venv/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in ./venv/lib/python3.14/site-packages (from seaborn) (2.4.3)
Requirement already satisfied: pandas>=1.2 in ./venv/lib/python3.14/site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in ./venv/lib/python3.14/site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in ./venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in ./venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [36]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [37]:
try:
    df = pd.read_csv("./data.csv")
except Exception as e:
    print("Error reading the data source file: e")
    quit()

In [38]:
df.columns = [
    "id",
    "diagnostic",

    "radius_mean",
    "texture_mean",
    "perimeter_mean",
    "area_mean",
    "smoothness_mean",
    "compactness_mean",
    "concavity_mean",
    "concave_points_mean",
    "symmetry_mean",
    "fractal_dimension_mean",

    "radius_se",
    "texture_se",
    "perimeter_se",
    "area_se",
    "smoothness_se",
    "compactness_se",
    "concavity_se",
    "concave_points_se",
    "symmetry_se",
    "fractal_dimension_se",

    "radius_largest",
    "texture_largest",
    "perimeter_largest",
    "area_largest",
    "smoothness_largest",
    "compactness_largest",
    "concavity_largest",
    "concave_points_largest",
    "symmetry_largest",
    "fractal_dimension_largest",
]

df.head(3)

,id,diagnostic,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,...,radius_largest,texture_largest,perimeter_largest,area_largest,smoothness_largest,compactness_largest,concavity_largest,concave_points_largest,symmetry_largest,fractal_dimension_largest
0,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
1,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
2,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300

In [39]:
df = df.drop(['id'], axis=1)
df.head(3)

,diagnostic,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,...,radius_largest,texture_largest,perimeter_largest,area_largest,smoothness_largest,compactness_largest,concavity_largest,concave_points_largest,symmetry_largest,fractal_dimension_largest
0,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
1,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
2,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300

In [40]:
df['diagnostic'] = df['diagnostic'].str.replace("B", "0")
df['diagnostic'] = df['diagnostic'].str.replace("M", "1")
df['diagnostic'] = pd.to_numeric(df['diagnostic'])
df.head(3)

,diagnostic,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,...,radius_largest,texture_largest,perimeter_largest,area_largest,smoothness_largest,compactness_largest,concavity_largest,concave_points_largest,symmetry_largest,fractal_dimension_largest
0,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
1,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
2,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300

In [41]:
diagnostic_corr = df.corr()['diagnostic'].sort_values()
diagnostic_corr

smoothness_se               -0.066629
fractal_dimension_mean      -0.018099
symmetry_se                 -0.009170
texture_se                  -0.007024
fractal_dimension_se         0.076068
concavity_se                 0.252567
compactness_se               0.290866
fractal_dimension_largest    0.320983
symmetry_mean                0.327336
smoothness_mean              0.356276
concave_points_se            0.407293
symmetry_largest             0.413382
smoothness_largest           0.419731
texture_mean                 0.422146
texture_largest              0.461443
area_se                      0.546343
perimeter_se                 0.554416
radius_se                    0.565373
compactness_largest          0.589453
compactness_mean             0.595587
concavity_largest            0.658348
concavity_mean               0.695648
area_mean                    0.708389
radius_mean                  0.729376
area_largest                 0.732925
perimeter_mean               0.741887
radius_largest               0.775725
concave_points_mean          0.776369
perimeter_largest            0.782470
concave_points_largest       0.793181
diagnostic                   1.000000
Name: diagnostic, dtype: float64

In [42]:
diagnostic_corr.sort_values(ascending=False).head(10)

diagnostic                1.000000
concave_points_largest    0.793181
perimeter_largest         0.782470
concave_points_mean       0.776369
radius_largest            0.775725
perimeter_mean            0.741887
area_largest              0.732925
radius_mean               0.729376
area_mean                 0.708389
concavity_mean            0.695648
Name: diagnostic, dtype: float64

In [43]:
test_corr = diagnostic_corr.sort_values(ascending=False)

In [48]:
test_corr.index.values.tolist()

['diagnostic',
 'concave_points_largest',
 'perimeter_largest',
 'concave_points_mean',
 'radius_largest',
 'perimeter_mean',
 'area_largest',
 'radius_mean',
 'area_mean',
 'concavity_mean',
 'concavity_largest',
 'compactness_mean',
 'compactness_largest',
 'radius_se',
 'perimeter_se',
 'area_se',
 'texture_largest',
 'texture_mean',
 'smoothness_largest',
 'symmetry_largest',
 'concave_points_se',
 'smoothness_mean',
 'symmetry_mean',
 'fractal_dimension_largest',
 'compactness_se',
 'concavity_se',
 'fractal_dimension_se',
 'texture_se',
 'symmetry_se',
 'fractal_dimension_mean',
 'smoothness_se']

In [ ]:
diagnostic_corr.sort_values().head(5)

In [ ]:
sns.pairplot(
    df,
    x_vars=['diagnostic'],
    y_vars=['concave_points_largest', 'perimeter_largest', 'concave_points_mean'],
    kind='hist'
)

In [ ]:
sns.pairplot(
    df,
    x_vars=['diagnostic'],
    y_vars=['fractal_dimension_se'],
    kind='hist'
)

In [ ]:
filtered_df = df[['diagnostic',
        'concave_points_largest',
        'perimeter_largest',
        'concave_points_mean',
        'radius_largest',
        'perimeter_mean',
        'area_largest',
        'radius_mean',
        'area_mean',
        'concavity_mean']]

df = df[[
    "diagnostic",
    "concavity_se",
    "compactness_se",
    "fractal_dimension_largest",
    "symmetry_mean",
    "smoothness_mean",
    "concave_points_se",
    "symmetry_largest",
    "smoothness_largest",
    "texture_mean",
    "texture_largest",
    "area_se",
    "perimeter_se",
    "radius_se",
    "compactness_largest",
    "compactness_mean",
    "concavity_largest",
    "concavity_mean",
    "area_mean",
    "radius_mean",
    "area_largest",
    "perimeter_mean",
    "radius_largest",
    "concave_points_mean",
    "perimeter_largest",
    "concave_points_largest"
]]

df.head(3)

In [ ]:
for col in df.columns:
  df[col] = pd.to_numeric(df[col])
  df[col] = df[col] / df[col].max()
df.head()

In [ ]:
for col in filtered_df.columns:
  filtered_df[col] = pd.to_numeric(df[col])
  filtered_df[col] = filtered_df[col] / filtered_df[col].max()

In [ ]:

np.random.seed(0)

mask = np.random.rand(len(df)) < 0.8

train = df[mask].to_numpy().astype(np.float64)
test = df[~mask].to_numpy().astype(np.float64)

print(len(test))
print(len(train))

In [ ]:
filtered_train = filtered_df[mask].to_numpy().astype(np.float64)
filtered_test = filtered_df[~mask].to_numpy().astype(np.float64)

In [ ]:
def softmax(o):
  def inner_softmax(x):
    return x / o.sum()
  softed_o = inner_softmax(o)
  return softed_o

In [ ]:
def get_loss_cee(predictions, expected):
  def inner_cee(p, y):
    return y * np.log(p) + (1 - y) * np.log(1 - p)
  loss = inner_cee(predictions, expected)
  loss = loss.sum() * -1 / len(predictions)

  return loss

In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def derivated_sigmoid(x):
  return sigmoid(x) * (1 - sigmoid(x))

In [ ]:
class Layer:

  def __init__(self, neurons_count, input_size, previous_layer=None, parameters=None):
    self.neurons_count = neurons_count

    if parameters:
        self.W = np.array(parameters["weights"])
        self.b = np.array(parameters["biases"])
    else:
        self.W = np.random.rand(neurons_count, input_size)
        self.b = np.zeros(neurons_count).reshape(neurons_count, 1)

    self.z = None
    self.A = None
    self.C = None

    self.previous_layer = previous_layer
    if self.previous_layer:
      self.previous_layer.next_layer = self

    self.next_layer = None
    self.incoming_A = None
    self.delta = None

  def forward_pass(self, a, result=False):
    self.incoming_A = a

    self.z = np.matmul(self.W, self.incoming_A) + self.b

    self.A = sigmoid(self.z)
    if self.next_layer:
      return self.next_layer.forward_pass(self.A, result=result)

    return softmax(self.A)

  def set_delta(self, expected_y=None):

    if self.next_layer is None:
      dL = 2 * (self.A - expected_y)
      self.delta = dL * derivated_sigmoid(self.z)

    else:
      self.delta = np.transpose(self.next_layer.W) @ self.next_layer.delta * derivated_sigmoid(self.z)

    if self.previous_layer:
      self.previous_layer.set_delta()

  def set_c(self):
    self.C = self.delta @ np.transpose(self.incoming_A)
    if self.previous_layer:
      self.previous_layer.set_c()


  def adjust_weights(self):
    self.W = self.W - (LEARNING_RATE * self.C)
    if self.previous_layer:
      self.previous_layer.adjust_weights()

  def adjust_biases(self):
      self.b = self.b - (LEARNING_RATE * self.delta)
      if self.previous_layer:
          self.previous_layer.adjust_biases()

  def get_parameters(self):

        neurons = []

        for (w, b) in zip(self.W, self.b):
            neurons.append({
                "weights": w.tolist(),
                "biases": b.tolist()
            })

        return {
            "neurons_count": self.neurons_count,
            "weights": self.W.tolist(),
            "biases": self.b.tolist(),
        }

In [ ]:
class NN:

    def load_model(self, model):

        self.architecture = model['architecture']['layers_architecture']
        self.features_count = model['architecture']['features_count']

        self.layers = []
        current_layer = None
        for l in model["layers"]:
            current_layer = Layer(neurons_count=l["neurons_count"],
                                  input_size=len(l["weights"][0]),
                                  previous_layer=current_layer,
                                  parameters=l)
            self.layers.append(current_layer)

        self.input_layer = self.layers[0]
        self.output_layer = self.layers[-1]


    def __init__(self, *args, model_to_load=None):
        if model_to_load:
            self.load_model(model_to_load)
            return

        if len(args) <= 1:
            raise Exception("The neural network should have at least one layer")

        self.features_count = int(args[0])
        self.architecture = [int(x) for x in args[1:]]

        self.layers = []

        current_layer = None
        for i, neurons_count in enumerate(self.architecture):
            current_layer = Layer (
                neurons_count=neurons_count,
                input_size=args[i],
                previous_layer=current_layer,
            )
            self.layers.append(current_layer)

        self.input_layer = self.layers[0]
        self.output_layer = self.layers[-1]


    def init_forward_pass(self, x):
        return self.input_layer.forward_pass(x)


    def init_back_propagation(self, expected_y):
        self.output_layer.set_delta(expected_y=expected_y)
        self.output_layer.set_c()
        self.output_layer.adjust_weights()
        self.output_layer.adjust_biases()


    def get_model(self):
        model = {
            "architecture": {
                "features_count": self.features_count,
                "output_count": self.architecture[-1],
                "layers_architecture": self.architecture
            },
            "layers_count": len(self.layers),
            "layers": []
        }

        for l in self.layers:
            model["layers"].append(l.get_parameters())

        return model

In [ ]:
MAX_EPOCH = 10000
PATIENCE = 50
WARMING_EPOCH = 100
LEARNING_RATE = 0.01

In [ ]:
FEATURES_COUNT = len(train[0]) - 1
EPOCH_COUNT = 0

try:
    nn = NN(FEATURES_COUNT,16,8,2)
except Exception as e:
    print(e)
    quit()

best_model = {
    "loss": None,
    "model": None,
}

len_train = len(train)
len_test = len(test)

evolution_accuracy = []
evolution_train_loss = []
evolution_test_loss = []

p = 0

def test_model(nn, test_set):
    cumulate_loss = 0
    correct_output = 0
    for i, in_value in enumerate(test_set):
        X = np.reshape(in_value[1:], (FEATURES_COUNT, 1))
        r = nn.init_forward_pass(X)
        cumulate_loss += get_loss_cee(r, np.array([[in_value[0]], [1 - in_value[0]]]))
        if bool(r[0] < r[1]) ^ bool(in_value[0]):
            correct_output += 1

    accuracy = correct_output / len(test_set)
    loss = cumulate_loss / len(test_set)

    return accuracy, loss


for x in range(MAX_EPOCH):
    cumulate_train_loss = 0
    for i, v in enumerate(train):
        X = np.reshape(v[1:], (FEATURES_COUNT, 1))
        r = nn.init_forward_pass(X)
        nn.init_back_propagation(np.array([[v[0]], [1 - v[0]]]))
        cumulate_train_loss += get_loss_cee(r, np.array([[v[0]], [1 - v[0]]]))


    train_loss = cumulate_train_loss / len_train

    epoch_accuracy, test_loss = test_model(nn, test)

    evolution_accuracy.append(epoch_accuracy)
    evolution_train_loss.append(train_loss)
    evolution_test_loss.append(test_loss)

    EPOCH_COUNT += 1

    if best_model["loss"] is None or test_loss < best_model["loss"]:
        best_model["loss"] = test_loss
        best_model["model"] = nn.get_model()
        p = 0

    elif x > WARMING_EPOCH and test_loss > best_model["loss"] + 0.01:
        p += 1

    if p > PATIENCE:
        break

    if x % 10 == 0:
        print(f"train_L = {train_loss:.3f}  val_L = {test_loss:.3f} acc = {epoch_accuracy:.2f}")

In [ ]:
# FEATURES_COUNT = len(filtered_train[0]) - 1
#
# firstNN = NN(
#     FEATURES_COUNT,
#     16,
#     8,
#     2
# )
#
# len_train = len(filtered_train)
# len_test = len(filtered_test)
#
# filtered_evolution_accuracy = []
# filtered_evolution_train_loss = []
# filtered_evolution_test_loss = []
#
# for x in range(MAX_EPOCH):
#     train_loss = 0
#     for i, v in enumerate(filtered_train):
#         X = np.reshape(v[1:], (FEATURES_COUNT, 1))
#         r = firstNN.init_forward_pass(X)
#         firstNN.init_back_propagation(np.array([[v[0]], [1 - v[0]]]))
#         train_loss += get_loss_cee(r, np.array([[v[0]], [1 - v[0]]]))
#     test_loss = 0
#     epoch_accuracy = 0
#     for i, v in enumerate(filtered_test):
#         X = np.reshape(v[1:], (FEATURES_COUNT, 1))
#         r = firstNN.init_forward_pass(X)
#         test_loss += get_loss_cee(r, np.array([[v[0]], [1 - v[0]]]))
#         if bool(r[0] < r[1]) ^ bool(v[0]):
#             epoch_accuracy += 1
#
#     filtered_evolution_accuracy.append(epoch_accuracy)
#     filtered_evolution_train_loss.append(train_loss / len_train)
#     filtered_evolution_test_loss.append(test_loss / len_test)
#
#     # if x % 100 == 0:
#     #     print(f"train_L = {train_loss / len_train:.3f}  val_L = {test_loss / len_test:.3f} acc = {epoch_accuracy} /  {len_test}")

In [ ]:
plt.plot(np.arange(1, EPOCH_COUNT + 1, 1), np.array(evolution_accuracy), color='r')
# plt.plot(np.arange(1, MAX_EPOCH + 1, 1), np.array(filtered_evolution_accuracy), color='b')

In [ ]:
plt.plot(np.arange(1, EPOCH_COUNT + 1, 1), np.array(evolution_train_loss), 'r')
plt.plot(np.arange(1, EPOCH_COUNT + 1, 1), np.array(evolution_test_loss), 'r--')
# plt.plot(np.arange(1, MAX_EPOCH + 1, 1), np.array(filtered_evolution_train_loss), color='yellow')
# plt.plot(np.arange(1, MAX_EPOCH + 1, 1), np.array(filtered_evolution_test_loss), color='orange')
plt.show()

In [ ]:
from pathlib import Path
import json

def save_model(filename, model=None, nn=None):
    if not model:
        if nn:
            model = nn.get_model()
        else:
            raise Exception("Defined model or NN object required to save the model")

    output_file = Path(f"./models/{filename}.txt")

    if not output_file.exists():
        output_file.parent.mkdir(exist_ok=True, parents=True)

    print(f"SAVING MODEL INTO {output_file.absolute()}")

    try:
        with output_file.open('w') as f:
            json.dump(model, f)
    except Exception as e:
        raise Exception(f"Error writing into {output_file.absolute()}: {e}")

In [ ]:
print(best_model)

In [ ]:
save_model("test", best_model["model"])

In [ ]:
def file_to_model(filename):
    input_file = Path(f"./models/{filename}")

    if not input_file.exists():
        raise Exception(f"{input_file.absolute()}: Model file doesnt exists")

    raw_content = input_file.read_text()

    if not raw_content:
        raise Exception(f"{input_file.absolute()}: model couldnt be read")

    model = json.loads(raw_content)

    return model

In [ ]:
loaded_model = file_to_model("test.txt")

In [ ]:
nn = NN(model_to_load=loaded_model)

In [ ]:
accuracy, loss = test_model(nn, test)

In [ ]:
print(accuracy, loss)